### ISSUE TITLE
Change rate graphs to something meaningfull

### ISSUE THREAD

**Issue by woutslakhorst** [nuts-foundation/performance-test#2]
for example the CPU rate graph shows the "rate" in seconds. These are actually percentages because the rate is calculated over 60s. A rate of 2 seconds means 1/30 or ~3% CPU usage.

Same goes for other "rates" like disk usage.

**Comment by gerardsn** [comment]
According to [documentation](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate) the rate is the `per-second average`, so I think a CPU rate of 2s means that it uses 2CPU seconds per second (on average over the interval, which should be set to 1 min everywhere).

This of course all depends on the number of CPU cores available to the container. Using a percentage on the rate graphs would hide the actual amount of resources used, while the current metric hides how much of the available resources are being used. The last one is only a problem when it hits resource limits.

**Comment by woutslakhorst** [comment]
We have to adjust the human in this issue ;)
